Repository Pocket/pocket-ios, pull requests merged in 2023-04, with the labels that each got.

#574 Fix - Add missing context injection
  PocketKit/Sources/Sync/RemoteMapping/Item+remoteMapping.swift
Labels: bug, Core Data

#594 Core Data - Cleanup Source, PocketSource
  PocketKit/Sources/Sync/PocketSource.swift
  PocketKit/Sources/Sync/Source.swift
Labels: Core Data

#596 Premium subscriptions: avoid checking subscriptions and sending receipts when logged out
  PocketKit/Sources/PocketKit/PremiumUpgrade/Model/PocketSubscriptionStore.swift
  PocketKit/Sources/PocketKit/PremiumUpgrade/Model/SubscriptionStore.swift
  PocketKit/Sources/PocketKit/Services.swift
  PocketKit/Sources/SharedPocketKit/User.swift
Labels: Premium Subscriptions, refactor

#620 Premium subscriptions - revert to free if subscription expired
  PocketKit/Sources/PocketKit/PremiumUpgrade/Model/PocketSubscriptionStore.swift
Labels: bug, Premium Subscriptions

#639 Core Data - Add `mergeByPropertyObjectTrump` to child contexts
  PocketKit/Sources/Sync/Space/Space.swift
Labels: bug, Core Data

#665 fix(saved-item): ensuring saved item only is pulled by url
  PocketKit/Sources/PocketKit/MyList/ItemsList/PocketItemViewModel.swift
  PocketKit/Sources/PocketKit/MyList/SearchItemsList/SearchViewModel.swift
  PocketKit/Sources/Sync/PocketSource.swift
  PocketKit/Sources/Sync/Requests.swift
  PocketKit/Sources/Sync/Source.swift
  PocketKit/Sources/Sync/Space/DerivedSpace.swift
  PocketKit/Sources/Sync/Space/Space.swift
  PocketKit/Tests/PocketKitTests/Support/MockSource.swift
  PocketKit/Tests/SyncTests/Fixtures/save-item.json
  PocketKit/Tests/SyncTests/Operations/SaveItemOperationTests.swift
  PocketKit/Tests/SyncTests/PocketSaveServiceTests.swift
  PocketKit/Tests/SyncTests/PocketSourceTests.swift
  PocketKit/Tests/SyncTests/Support/FetchSavesTests.swift
Labels: Core Data

#669 App Store Receipt - prevent continuations to be overwritten so they can safely be resumed and deleted
  PocketKit/Sources/PocketKit/PremiumUpgrade/Model/ReceiptService.swift
Labels: Premium Subscriptions

#672 When capturing an error, log the error instead of the localized description
  PocketKit/Sources/SharedPocketKit/Log.swift
Labels: Logging
