Repository Pocket/pocket-ios, pull requests merged in 2025-01, with the labels that each got.

#1133 Fix SwiftData crash due to SwiftData missing relationships in certain conditions.
  PocketKit/Sources/PocketKit/Home/Views/Card groups/SlateView.swift
  PocketKit/Sources/PocketKit/Home/Views/Detail views/SharedWithYouDetailView.swift
  PocketKit/Sources/PocketKit/Home/Views/Detail views/SlateDetailView.swift
  PocketKit/Sources/PocketKit/Home/Views/Navigation/NavigationDestination.swift
  PocketKit/Sources/PocketKit/Home/Views/Top level views/RecentSavesView.swift
  PocketKit/Sources/PocketKit/Home/Views/Top level views/RecommendationsView.swift
  PocketKit/Sources/PocketKit/Home/Views/Top level views/SharedWithYouView.swift
Labels: SwiftData, crash

#1135 fix(search): ensure no empty object is passed via search filters
  PocketKit/Sources/Sync/Operations/SearchService.swift
  PocketKit/Tests/SyncTests/Support/PocketSearchServiceTests.swift
  Tests iOS/HomeTests.swift
Labels: bug, Search

#1137 Release bump + dependencies update
  Pocket.xcodeproj/project.pbxproj
  Pocket.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: dependencies, release bump

#1138 Add graphQl queries and mutations for Notes
  PocketKit/Sources/PocketGraph/Fragments/NotesPart.graphql.swift
  PocketKit/Sources/PocketGraph/Operations/Mutations/CreateNoteMarkdownMutation.graphql.swift
  PocketKit/Sources/PocketGraph/Operations/Mutations/DeleteNoteMutation.graphql.swift
  PocketKit/Sources/PocketGraph/Operations/Mutations/EditNoteContentMarkdownMutation.graphql.swift
  PocketKit/Sources/PocketGraph/Operations/Mutations/EditNoteTitleMutation.graphql.swift
  PocketKit/Sources/PocketGraph/Operations/Queries/NoteQuery.graphql.swift
  PocketKit/Sources/PocketGraph/Operations/Queries/NotesQuery.graphql.swift
  PocketKit/Sources/PocketGraph/Schema/Enums/VideoType.graphql.swift
  PocketKit/Sources/PocketGraph/Schema/InputObjects/CreateNoteMarkdownInput.graphql.swift
  PocketKit/Sources/PocketGraph/Schema/InputObjects/DeleteNoteInput.graphql.swift
  PocketKit/Sources/PocketGraph/Schema/InputObjects/EditNoteContentMarkdownInput.graphql.swift
  PocketKit/Sources/PocketGraph/Schema/InputObjects/EditNoteTitleInput.graphql.swift
  PocketKit/Sources/PocketGraph/Schema/Objects/Note.graphql.swift
  PocketKit/Sources/PocketGraph/Schema/Objects/NoteConnection.graphql.swift
  PocketKit/Sources/PocketGraph/Schema/Objects/NoteEdge.graphql.swift
  PocketKit/Sources/PocketGraph/Schema/SchemaMetadata.graphql.swift
  PocketKit/Sources/PocketGraph/user-defined-operations/notes.graphql
  PocketKit/Sources/PocketGraphTestMocks/Mutation+Mock.graphql.swift
  PocketKit/Sources/PocketGraphTestMocks/Note+Mock.graphql.swift
  PocketKit/Sources/PocketGraphTestMocks/NoteConnection+Mock.graphql.swift
  PocketKit/Sources/PocketGraphTestMocks/NoteEdge+Mock.graphql.swift
  PocketKit/Sources/PocketGraphTestMocks/Query+Mock.graphql.swift
Labels: Notes

#1141 Fix some crashes
  PocketKit/Sources/PocketKit/Home/Models/HomeActions.swift
  PocketKit/Sources/PocketKit/Home/Views/Detail views/SlateDetailView.swift
  PocketKit/Sources/PocketKit/Home/Views/Top level views/RecentSavesView.swift
  PocketKit/Sources/PocketKit/Home/Views/Top level views/RecommendationsView.swift
  PocketKit/Sources/Sync/PocketSource.swift
  PocketKit/Sources/Sync/Source.swift
  PocketKit/Tests/PocketKitTests/Support/MockSource.swift
Labels: Home, SwiftData, SwiftUI, crash

#1142 fix note asset name
  PocketKit/Sources/Textile/Style/Images/Images.xcassets/notes.imageset/Contents.json
  PocketKit/Sources/Textile/Style/Images/Images.xcassets/notes.imageset/pocket-note-icon.pdf
Labels: chore

#1143 Release bump
  Pocket.xcodeproj/project.pbxproj
  Pocket.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: dependencies, release bump

#1144 remove formatting from notes preview
  PocketKit/Sources/PocketKit/MyList/ItemsList/UIKit/Cells/NoteListCell.swift
  PocketKit/Sources/PocketKit/MyList/ItemsList/UIKit/NoteListPresenter.swift
  PocketKit/Sources/PocketKit/MyList/ItemsList/UIKit/SavedItemsList/SavedItemsListViewModel.swift
Labels: Notes
